from logging import raiseExceptions
import unittest

class TestClass14(unittest.TestCase):
    def test_Case01(self):
        raise Exception